name: Tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test_mysql:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root123
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 3306:3306

    strategy:
      fail-fast: false
      matrix:
        include:
          ### RAILS VERSION TESTING
          ### DONT WORRY ABOUT TESTING ALL RUBY VERSIONS. THIS IS COVERED IN THE SQLITE3 TESTS
          - ruby: 2.6
            gemfile: gemfiles/Gemfile.4.2.mysql2
          - ruby: 2.6
            gemfile: gemfiles/Gemfile.5.0.mysql2
          - ruby: 2.6
            gemfile: gemfiles/Gemfile.5.1.mysql2
          - ruby: 2.6
            gemfile: gemfiles/Gemfile.5.2.mysql2
          - ruby: 2.6
            gemfile: gemfiles/Gemfile.6.0.mysql2
          - ruby: 2.6
            gemfile: gemfiles/Gemfile.6.1.mysql2

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - uses: actions/checkout@v2

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"

    - name: Setup database
      run: |
        sudo apt-get install -y mysql-client libmariadbclient-dev
        mysql -e 'create database IF NOT EXISTS test;' -u root --password=password -P 3306 -h 127.0.0.1

    - name: Bundle
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: bundle exec rake

  test_pg:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5"
        ports:
        - 5432:5432

    strategy:
      fail-fast: false
      matrix:
        include:
        ### RAILS VERSION TESTING
        ### DONT WORRY ABOUT TESTING ALL RUBY VERSIONS. THIS IS COVERED IN THE SQLITE3 TESTS
        - ruby: 2.6
          gemfile: gemfiles/Gemfile.4.2.pg
        - ruby: 2.6
          gemfile: gemfiles/Gemfile.5.0.pg
        - ruby: 2.6
          gemfile: gemfiles/Gemfile.5.1.pg
        - ruby: 2.6
          gemfile: gemfiles/Gemfile.5.2.pg
        - ruby: 2.6
          gemfile: gemfiles/Gemfile.6.0.pg
        - ruby: 2.6
          gemfile: gemfiles/Gemfile.6.1.pg

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    steps:
    - uses: actions/checkout@v2

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"

    - name: Setup database
      run: |
        sudo apt-get install -y postgresql-client
        PGPASSWORD=postgres psql -c 'create database test;' -U postgres -p 5432 -h localhost

    - name: Bundle
      run: |
        gem install bundler
        bundle install

    - name: Run tests
      run: bundle exec rake

  test_sqlite:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        ### TEST ALL RUBY VERSIONS, USE DEFAULT GEMFILE
        - ruby: 2.3
        - ruby: 2.4
        - ruby: 2.5
        - ruby: 2.6
        - ruby: 2.7
        - ruby: 3.0

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    steps:
    - uses: actions/checkout@v2

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"

    - name: Bundle
      run: |
        gem install bundler
        bundle install 

    - name: Run tests
      run: bundle exec rake
